### ISSUE TITLE
Provide advisory when lora target modules dont exist

### ISSUE THREAD

**Issue by RobotSail** [instructlab/training#164]
When the LoRA target modules don't exist, we should figure out what modules we're missing and advise the user to update their target modules.

**Comment by RobotSail** [comment]
Specifically, when the user encounters this as an error it will emit from https://github.com/instructlab/training/blob/0975568e3d6dae922b1c1bc11e8b5173c063f980/src/instructlab/training/utils.py#L352


And have a stack trace as follows:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 781, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 560, in main
[rank0]:     model = setup_model(args, tokenizer, train_loader, grad_accum)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/instructlab/training/main_ds.py", line 194, in setup_model
[rank0]:     model = prepare_peft_model(
[rank0]:             ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/instructlab/training/utils.py", line 352, in prepare_peft_model
[rank0]:     model = get_peft_model(model, peft_config)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/peft/mapping.py", line 183, in get_peft_model
[rank0]:     return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/peft/peft_model.py", line 1542, in __init__
[rank0]:     super().__init__(model, peft_config, adapter_name, **kwargs)
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/peft/peft_model.py", line 155, in __init__
[rank0]:     self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/peft/tuners/lora/model.py", line 139, in __init__
[rank0]:     super().__init__(model, config, adapter_name)
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/peft/tuners/tuners_utils.py", line 175, in __init__
[rank0]:     self.inject_adapter(self.model, adapter_name)
[rank0]:   File "/home/ec2-user/training/venv/lib64/python3.11/site-packages/peft/tuners/tuners_utils.py", line 435, in inject_adapter
[rank0]:     raise ValueError(
[rank0]: ValueError: Target modules {'v_proj', 'k_proc', 'o_proj', 'q_proj'} not found in the base model. Please check the target modules and try again.
```
