### ISSUE TITLE
Division by zero error when calling `find_packing_max_batch_len_and_grad_accum`

### ISSUE THREAD

**Issue by RobotSail** [instructlab/training#254]
It seems like there's a division by zero error that can still occur with the right conditions.

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/oleg/Programming/training/src/instructlab/training/main_ds.py", line 934, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/oleg/Programming/training/src/instructlab/training/main_ds.py", line 546, in main
[rank0]:     packing_max_batch_len, grad_accum = find_packing_max_batch_len_and_grad_accum(
[rank0]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/oleg/Programming/training/src/instructlab/training/multipack_sampler.py", line 160, in find_packing_max_batch_len_and_grad_accum
[rank0]:     packing_max_batch_len = find_max_pack_len_with_padding(
[rank0]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/oleg/Programming/training/src/instructlab/training/multipack_sampler.py", line 86, in find_max_pack_len_with_padding
[rank0]:     avg_bs_per_minibatch = get_effective_samples_per_minibatch(
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/oleg/Programming/training/src/instructlab/training/multipack_sampler.py", line 79, in get_effective_samples_per_minibatch
[rank0]:     return len(dataset) / len(batches)
[rank0]:            ~~~~~~~~~~~~~^~~~~~~~~~~~~~
[rank0]: ZeroDivisionError: division by zero
```

To reproduce: 

1. Run a model train with the [community dataset](https://huggingface.co/datasets/instructlab/InstructLabCommunity)
2. Set your `TrainingArgs` like so:

```
train_args = TrainingArgs(
    data_path="path/to/data",
    is_padding_free=False,
    ckpt_output_dir='checkpoints',
    data_output_dir='/dev/shm',
    max_seq_len=70,
    max_batch_len=70,
    effective_batch_size=3840,
    save_samples=20_000,
)
```

**Comment by JamesKunstle** [comment]
@RobotSail I think you fixed this!
